[formatter.haskell]
command = "fourmolu"
options = [ "--mode", "inplace" ]
includes = [ "*.hs" ]
excludes = [ ]

[formatter.elm]
command = "elm-format"
options = [ "--elm-version", "0.19", "--yes" ]
includes = [ "*.elm" ]
excludes = [ "zulu/elmental/test-app/*", "zulu/elmental/test-output/*", "zulu/frontend/src/Flint/DTO/*", "mailbaboon/*", "profile/*"]


[formatter.nix]
command = "nixpkgs-fmt"
options = []
includes = ["*.nix"]
excludes = [ ]
